-- Disabled because it duplicated and seems LSP handles linting on its own
return {}
-- return {
--   'mfussenegger/nvim-lint',
--   event = { 'BufReadPre', 'BufNewFile' },
--   config = function()
--     local lint = require 'lint'
--
--     lint.linters_by_ft = {
--       javascript = { 'eslint' },
--       typescript = { 'eslint' },
--       javascriptreact = { 'eslint' },
--       typescriptreact = { 'eslint' },
--     }
--
--     local lint_augroup = vim.api.nvim_create_augroup('lint', { clear = true })
--
--     vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePost', 'InsertLeave' }, {
--       group = lint_augroup,
--       callback = function()
--         lint.try_lint()
--       end,
--     })
--
--     vim.keymap.set('n', '<leader>l', function()
--       lint.try_lint()
--     end, { desc = 'Trigger linting for current file' })
--   end,
-- }
