return {}
-- return {
--   'pmizio/typescript-tools.nvim',
--   dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
--   opts = {
--     settings = {
--       tsserver_file_preferences = {
--         includeCompletionsForImportStatements = true,
--         includeInlayParameterNameHints = 'all',
--         includeCompletionsForModuleExports = true,
--         quotePreference = 'auto',
--         includeInlayParameterNameHintsWhenArgumentMatchesName = false,
--         includeInlayFunctionParameterTypeHints = true,
--         includeInlayVariableTypeHints = true,
--         includeInlayVariableTypeHintsWhenTypeMatchesName = false,
--         includeInlayPropertyDeclarationTypeHints = true,
--         includeInlayFunctionLikeReturnTypeHints = true,
--         includeInlayEnumMemberValueHints = true,
--         displayPartsForJSDoc = true,
--         generateReturnInDocTemplate = true,
--       },
--     },
--   },
-- }
