return {
  "catppuccin/nvim",
  name = "catppuccin",
  lazy = false,
  opts = {
    transparent_background = true,
    integrations = {
      telescope = true,
      mason = true,
      flash = true,
      dashboard = true,
      treesitter = true,
      which_key = true,
      markdown = true,
      cmp = true,
      notify = true,
      mini = { enabled = true, indentscope_color = "" },
      color_overrides = {
        mocha = {
          base = "#1c1917",
          blue = "#22d3ee",
          green = "#86efac",
          flamingo = "#D6409F",
          lavender = "#DE51A8",
          pink = "#f9a8d4",
          red = "#fda4af",
          maroon = "#f87171",
          mauve = "#D19DFF",
          text = "#E8E2D9",
          sky = "#7ee6fd",
          yellow = "#fde68a",
          rosewater = "#f4c2c2",
          peach = "#fba8c4",
          teal = "#4fd1c5",
        },
      },
    },
  },
}
